apiVersion: v1
kind: Service
metadata:
  name: webapp-demo-service
  namespace: gitops-app
  labels:
    app: webapp-demo
spec:
  type: ClusterIP
  selector:
    app: webapp-demo
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP